In [ ]:
"""
djenkins$ conda install -c conda-forge quaternion
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.7.10
  latest version: 4.8.0

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: //anaconda3

  added / updated specs:
    - quaternion



The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.8.0                |           py37_1         3.0 MB  conda-forge
    quaternion-2019.12.11.22.25.52|   py37h3b54f70_0          66 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         3.0 MB

The following NEW packages will be INSTALLED:

  quaternion         conda-forge/osx-64::quaternion-2019.12.11.22.25.52-py37h3b54f70_0

The following packages will be UPDATED:

  conda                      pkgs/main::conda-4.7.10-py37_0 --> conda-forge::conda-4.8.0-py37_1


Proceed ([y]/n)? y


Downloading and Extracting Packages
quaternion-2019.12.1 | 66 KB     | ########################################################################## | 100% 
conda-4.8.0          | 3.0 MB    | ########################################################################## | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
>>> import numpy as np
>>> import quaternion
//anaconda3/lib/python3.7/site-packages/llvmlite/binding/ffi.py:138: UserWarning: Module quaternion was already imported from //anaconda3/lib/python3.7/site-packages/quaternion/__init__.py, but /private/var/tmp/numpy-quaternion-2019.12.11.22.25.52 is being added to sys.path
  from pkg_resources import resource_filename
>>> np.quaternion(1,0,0,0)
quaternion(1, 0, 0, 0)
>>> q1 = np.quaternion(1,2,3,4)
>>> q2 = np.quaternion(5,6,7,8)
>>> q1 * q2
quaternion(-60, 12, 30, 24)
>>> a = np.array([q1, q2])
>>> a
array([quaternion(1, 2, 3, 4), quaternion(5, 6, 7, 8)], dtype=quaternion)
>>> exp(a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'exp' is not defined
>>> np.exp(a)
array([quaternion(1.6939227236833, -0.789559624541559, -1.18433943681234, -1.57911924908312),
       quaternion(138.909074085355, -25.6860834459456, -29.9670973536031, -34.2481112612607)],
      dtype=quaternion)
>>> print(quaternion.quaternion.__doc__)
Floating-point quaternion numbers
>>> print(quaternion.__doc__)
Adds a quaternion dtype to NumPy.
>>> print(quaternion.quaternion.isnan.__doc__)
True if the quaternion has any NAN components
>>> print(quaternion.quaternion.isinf.__doc__)
True if the quaternion has any INF components
>>> b = np.random.rand(7, 4)
>>> a
array([quaternion(1, 2, 3, 4), quaternion(5, 6, 7, 8)], dtype=quaternion)
>>> b
array([[0.99895373, 0.30154827, 0.88115152, 0.98287508],
       [0.49534313, 0.61018186, 0.9096572 , 0.29204415],
       [0.39470414, 0.11470446, 0.65476301, 0.21670401],
       [0.17782326, 0.97546319, 0.91501829, 0.58850964],
       [0.5403809 , 0.80178664, 0.79783456, 0.21799257],
       [0.77595376, 0.01932171, 0.33732108, 0.45163488],
       [0.60139502, 0.97799766, 0.87209139, 0.16686438]])
>>> qs = quaternion.as_quat_array(b)
>>> qs
array([quaternion(0.998953731683471, 0.301548271773422, 0.881151522076046, 0.982875077757529),
       quaternion(0.495343129122788, 0.610181856859035, 0.909657196953155, 0.292044147129649),
       quaternion(0.394704137986282, 0.114704459225541, 0.654763010521751, 0.216704014056125),
       quaternion(0.177823258485604, 0.975463185507288, 0.915018285395388, 0.588509644908966),
       quaternion(0.540380896317057, 0.80178663747606, 0.797834556149534, 0.217992566846626),
       quaternion(0.775953757406735, 0.0193217087005647, 0.337321078753476, 0.451634882827485),
       quaternion(0.60139502036291, 0.97799766439602, 0.872091393520252, 0.166864381115203)],
      dtype=quaternion)
>>> c = quaternion.as_float_array(qs)
>>> c
array([[0.99895373, 0.30154827, 0.88115152, 0.98287508],
       [0.49534313, 0.61018186, 0.9096572 , 0.29204415],
       [0.39470414, 0.11470446, 0.65476301, 0.21670401],
       [0.17782326, 0.97546319, 0.91501829, 0.58850964],
       [0.5403809 , 0.80178664, 0.79783456, 0.21799257],
       [0.77595376, 0.01932171, 0.33732108, 0.45163488],
       [0.60139502, 0.97799766, 0.87209139, 0.16686438]])
>>> q1 * q1
quaternion(-28, 4, 6, 8)
>>> q2 * q2
quaternion(-124, 60, 70, 80)
>>> q2 * q1
quaternion(-60, 20, 14, 32)
"""

In [1]:
import numpy as np

In [2]:
np.quaternion(1,0,0,0)

AttributeError: module 'numpy' has no attribute 'quaternion'

In [3]:
import quaternion

In [5]:
np.quaternion(1,0,0,0)

quaternion(1, 0, 0, 0)

In [6]:
q1 = np.quaternion(1,2,3,4)
q2 = np.quaternion(5,6,7,8)

In [7]:
q1 * q2

quaternion(-60, 12, 30, 24)

In [8]:
a = np.array([q1, q2])

In [9]:
a

array([quaternion(1, 2, 3, 4), quaternion(5, 6, 7, 8)], dtype=quaternion)

In [10]:
np.exp(a)

array([quaternion(1.6939227236833, -0.789559624541559, -1.18433943681234, -1.57911924908312),
       quaternion(138.909074085355, -25.6860834459456, -29.9670973536031, -34.2481112612607)],
      dtype=quaternion)

In [11]:
b = np.random.rand(7, 4)

In [16]:
b

array([[0.47625742, 0.21629489, 0.49112037, 0.81027465],
       [0.6725208 , 0.58919041, 0.82025083, 0.82597669],
       [0.70320494, 0.19602951, 0.03348806, 0.94086097],
       [0.74003941, 0.77189059, 0.62692237, 0.63263106],
       [0.32140599, 0.30951684, 0.07298492, 0.48303013],
       [0.69059116, 0.1071121 , 0.34334277, 0.00382687],
       [0.24372803, 0.45613818, 0.70021532, 0.80523109]])

In [12]:
qa = quaternion.as_quat_array(b)

In [13]:
qa

array([quaternion(0.476257420851741, 0.216294887839965, 0.491120370003263, 0.810274649430499),
       quaternion(0.67252079848163, 0.589190405072833, 0.820250833916818, 0.825976691445323),
       quaternion(0.703204938671097, 0.196029510349619, 0.0334880557614015, 0.940860965281321),
       quaternion(0.74003941153208, 0.771890593739248, 0.626922369982536, 0.632631056702392),
       quaternion(0.321405989295709, 0.309516844535901, 0.0729849190346288, 0.4830301331896),
       quaternion(0.690591162059323, 0.107112095533329, 0.343342768717331, 0.00382687291932882),
       quaternion(0.243728032590521, 0.456138183616873, 0.700215316682061, 0.805231089852701)],
      dtype=quaternion)

In [14]:
c = quaternion.as_float_array(qa)

In [15]:
c

array([[0.47625742, 0.21629489, 0.49112037, 0.81027465],
       [0.6725208 , 0.58919041, 0.82025083, 0.82597669],
       [0.70320494, 0.19602951, 0.03348806, 0.94086097],
       [0.74003941, 0.77189059, 0.62692237, 0.63263106],
       [0.32140599, 0.30951684, 0.07298492, 0.48303013],
       [0.69059116, 0.1071121 , 0.34334277, 0.00382687],
       [0.24372803, 0.45613818, 0.70021532, 0.80523109]])

In [17]:
q2 * q1

quaternion(-60, 20, 14, 32)

In [18]:
#1*5 + 1*6i + 1*7j + 1*8k + 2*5i - 2*6 + 2*7k - 2*8j + 3*5j - 3*6k - 3*7 +3*8i + 4*5k + 4*6j - 4*7i -4*8

#    5   +  6i +  7j +  8k
# -12 + 10i - 16j + 14k
# -21 + 24i + 15j - 18k
# -32 - 28i + 24j + 20k
# -60 + 12i + 30j + 24k

In [19]:
http://www.zpenergy.com/downloads/Orig_maxwell_equations.pdf
https://www.mathworks.com/help/fusion/ref/quaternion.mtimes.html

SyntaxError: invalid syntax (<ipython-input-19-084fe069418d>, line 1)

In [20]:
q2 * q1

quaternion(-60, 20, 14, 32)