# Pandas Data Cleaning and Exploratory Data Analysis (EDA)

In [1]:
import pandas as pd

In [2]:
# Feature to save nb output to xls format
# pip install nb2xls

## Upload Data

In [3]:
housing_header = ["HomeID", "HomeAge", "HomeSqft", "LotSize", "BedRooms", 
                  "HighSchoolAPI", "ProxFwy", "CarGarage", "ZipCode", "HomePriceK"]
df = pd.read_csv("fixed-housing-data.csv",names=housing_header)
#what does this do?

In [4]:
df.head()

HomeID  HomeAge  HomeSqft  LotSize  BedRooms  HighSchoolAPI  ProxFwy  \
0       1       24      1757     6056         2            899        3   
1       2       10      1563     6085         2            959        4   
2       3       14      1344     6089         2            865        4   
3       4       14      1215     6129         3            959        4   
4       5       24      1866     6141         3            877        4   

   CarGarage  ZipCode  HomePriceK  
0          3    94085         894  
1          3    94085         861  
2          3    94085         831  
3          2    94085         809  
4          1    94085         890

In [5]:
df.tail()

HomeID  HomeAge  HomeSqft  LotSize  BedRooms  HighSchoolAPI  ProxFwy  \
95      96       11      1981     9350         4            912        2   
96      97       10      1645     9352         4            942        3   
97      98       21      1312     9456         4            915        4   
98      99       19      1880     9470         3            857        3   
99     100       11      1691     9476         4            857        4   

    CarGarage  ZipCode  HomePriceK  
95          1    95014        1307  
96          3    95014        1336  
97          3    95014        1284  
98          3    95014        1269  
99          0    95014        1250

Why did we only want to display the first 5 rows of the dataframe?

What if we wanted to see the size of this dataframe?

In [6]:
# number of rows
len(df)

100

In [7]:
# shape of df (rows, columns)
df.shape

(100, 10)

## Change Column Name(s)

Why would we want to change the column names?

In [8]:
df = df.rename(columns={'HighSchoolAPI': 'SchoolAPI'})
df.head()

HomeID  HomeAge  HomeSqft  LotSize  BedRooms  SchoolAPI  ProxFwy  \
0       1       24      1757     6056         2        899        3   
1       2       10      1563     6085         2        959        4   
2       3       14      1344     6089         2        865        4   
3       4       14      1215     6129         3        959        4   
4       5       24      1866     6141         3        877        4   

   CarGarage  ZipCode  HomePriceK  
0          3    94085         894  
1          3    94085         861  
2          3    94085         831  
3          2    94085         809  
4          1    94085         890

In [9]:
df = df.rename(columns={'LotSize': 'lotsize', 'SchoolAPI': 'schoolapi'})
df.head()

HomeID  HomeAge  HomeSqft  lotsize  BedRooms  schoolapi  ProxFwy  \
0       1       24      1757     6056         2        899        3   
1       2       10      1563     6085         2        959        4   
2       3       14      1344     6089         2        865        4   
3       4       14      1215     6129         3        959        4   
4       5       24      1866     6141         3        877        4   

   CarGarage  ZipCode  HomePriceK  
0          3    94085         894  
1          3    94085         861  
2          3    94085         831  
3          2    94085         809  
4          1    94085         890

In [10]:
df = df.rename(columns={'lotsize': 'LotSize', 'schoolapi': 'SchoolAPI'})
df.head()

HomeID  HomeAge  HomeSqft  LotSize  BedRooms  SchoolAPI  ProxFwy  \
0       1       24      1757     6056         2        899        3   
1       2       10      1563     6085         2        959        4   
2       3       14      1344     6089         2        865        4   
3       4       14      1215     6129         3        959        4   
4       5       24      1866     6141         3        877        4   

   CarGarage  ZipCode  HomePriceK  
0          3    94085         894  
1          3    94085         861  
2          3    94085         831  
3          2    94085         809  
4          1    94085         890

## Create New Columns

What is new information about "Block_Location" that we can actually use and save?

Let's create new columns for the information we extracted from those values.

In [11]:
prices_2019 = [(price * 1.04) for price in df["HomePriceK"]]
df["Price2019"] = prices_2019
df.head()

HomeID  HomeAge  HomeSqft  LotSize  BedRooms  SchoolAPI  ProxFwy  \
0       1       24      1757     6056         2        899        3   
1       2       10      1563     6085         2        959        4   
2       3       14      1344     6089         2        865        4   
3       4       14      1215     6129         3        959        4   
4       5       24      1866     6141         3        877        4   

   CarGarage  ZipCode  HomePriceK  Price2019  
0          3    94085         894     929.76  
1          3    94085         861     895.44  
2          3    94085         831     864.24  
3          2    94085         809     841.36  
4          1    94085         890     925.60

In [12]:
prices_2020 = [(price * 0.9) for price in df["HomePriceK"]]
df["Price2020"] = prices_2020

#Check if it worked
df.head()

HomeID  HomeAge  HomeSqft  LotSize  BedRooms  SchoolAPI  ProxFwy  \
0       1       24      1757     6056         2        899        3   
1       2       10      1563     6085         2        959        4   
2       3       14      1344     6089         2        865        4   
3       4       14      1215     6129         3        959        4   
4       5       24      1866     6141         3        877        4   

   CarGarage  ZipCode  HomePriceK  Price2019  Price2020  
0          3    94085         894     929.76      804.6  
1          3    94085         861     895.44      774.9  
2          3    94085         831     864.24      747.9  
3          2    94085         809     841.36      728.1  
4          1    94085         890     925.60      801.0

## Drop Columns

In [13]:
df = df.drop("ProxFwy", axis = 1)
#Check if it dropped
df.head()

HomeID  HomeAge  HomeSqft  LotSize  BedRooms  SchoolAPI  CarGarage  \
0       1       24      1757     6056         2        899          3   
1       2       10      1563     6085         2        959          3   
2       3       14      1344     6089         2        865          3   
3       4       14      1215     6129         3        959          2   
4       5       24      1866     6141         3        877          1   

   ZipCode  HomePriceK  Price2019  Price2020  
0    94085         894     929.76      804.6  
1    94085         861     895.44      774.9  
2    94085         831     864.24      747.9  
3    94085         809     841.36      728.1  
4    94085         890     925.60      801.0

In [14]:
aa= df.ZipCode.unique()
print(aa)

[94085 95051 94087 95014]


In [15]:
bb = df["CarGarage"].unique()
print(bb)

[3 2 1 0]


# EXPLORATORY DATA ANALYSIS

<h3>"Exploratory data analysis or 'EDA' is a <b>critical</b> beginning step in analyzing the data from an experiment.</h3>

<b>Here are the main reasons we use EDA:</b>
<ul>
• detection of mistakes<br><br>
• checking of assumptions<br><br>
• preliminary selection of appropriate models<br><br>
• determining relationships among the explanatory variables, and<br><br>
• assessing the direction and rough size of relationships between explanatory and outcome variables."</ul>


## Now what?

We have cleaned our data to the best of our ability based on the initial look. Now let's try to look at the <b>relationships</b> between different values. 

In [16]:
df.head()

HomeID  HomeAge  HomeSqft  LotSize  BedRooms  SchoolAPI  CarGarage  \
0       1       24      1757     6056         2        899          3   
1       2       10      1563     6085         2        959          3   
2       3       14      1344     6089         2        865          3   
3       4       14      1215     6129         3        959          2   
4       5       24      1866     6141         3        877          1   

   ZipCode  HomePriceK  Price2019  Price2020  
0    94085         894     929.76      804.6  
1    94085         861     895.44      774.9  
2    94085         831     864.24      747.9  
3    94085         809     841.36      728.1  
4    94085         890     925.60      801.0

In [17]:
df.describe()

HomeID     HomeAge     HomeSqft      LotSize   BedRooms  \
count  100.000000  100.000000   100.000000   100.000000  100.00000   
mean    50.500000   17.200000  1615.280000  7840.500000    2.71000   
std     29.011492    4.925711   231.759719  1046.107306    0.71485   
min      1.000000   10.000000  1215.000000  6056.000000    2.00000   
25%     25.750000   12.750000  1411.500000  7024.250000    2.00000   
50%     50.500000   17.000000  1606.500000  7822.000000    3.00000   
75%     75.250000   21.250000  1836.000000  8839.250000    3.00000   
max    100.000000   25.000000  1994.000000  9476.000000    4.00000   

        SchoolAPI   CarGarage       ZipCode   HomePriceK    Price2019  \
count  100.000000  100.000000    100.000000   100.000000   100.000000   
mean   904.430000    1.520000  94559.250000  1080.990000  1124.229600   
std     36.337713    1.234848    475.816351   146.533583   152.394926   
min    850.000000    0.000000  94085.000000   809.000000   841.360000   
25%    875.750000    0.000000  94086.500000   940.000000   977.600000   
50%    900.500000    2.000000  94550.500000  1100.000000  1144.000000   
75%    936.000000    3.000000  95023.250000  1191.000000  1238.640000   
max    975.000000    3.000000  95051.000000  1336.000000  1389.440000   

         Price2020  
count   100.000000  
mean    972.891000  
std     131.880224  
min     728.100000  
25%     846.000000  
50%     990.000000  
75%    1071.900000  
max    1202.400000

Let's look at the different types of offenses that were called in. We know that using the .unique() function will return all the unique values in the column, but what if we wanted to also <b>count</b> the different times each unique value appeared?

In [18]:
df.ZipCode.value_counts()

95051    25
95014    25
94087    25
94085    25
Name: ZipCode, dtype: int64

In [19]:
df.CarGarage.value_counts()

3    32
0    31
2    19
1    18
Name: CarGarage, dtype: int64

## GroupBy 

In [20]:
df1 = df.groupby("ZipCode").CarGarage.value_counts()
print(df1)

ZipCode  CarGarage
94085    3             8
         1             7
         2             6
         0             4
94087    0             9
         1             7
         3             5
         2             4
95014    3            11
         0             9
         2             3
         1             2
95051    0             9
         3             8
         2             6
         1             2
Name: CarGarage, dtype: int64


In [21]:
df1 = df.groupby("ZipCode")["CarGarage"].value_counts()
print(df1)

ZipCode  CarGarage
94085    3             8
         1             7
         2             6
         0             4
94087    0             9
         1             7
         3             5
         2             4
95014    3            11
         0             9
         2             3
         1             2
95051    0             9
         3             8
         2             6
         1             2
Name: CarGarage, dtype: int64


## More about GROUP BY
"This grouped variable is now a GroupBy object. It has not actually computed anything yet except for some intermediate data about the group key df['key1']. The idea is that this object has all of the information needed to then apply some operation to each of the groups." - Python for Data Analysis

In [22]:
#Use list() to show what a grouping looks like

df.groupby("ZipCode")

Descriptive statistics by group

In [24]:
#returns a dict of your groups
cc = df.groupby("ZipCode").groups
print(cc)
print(list(cc))

{94085: Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 16, 17,
            19, 20, 21, 22, 24, 25, 26, 28],
           dtype='int64'), 94087: Int64Index([40, 41, 45, 47, 48, 53, 55, 56, 57, 59, 60, 61, 62, 63, 64, 66, 67,
            68, 69, 71, 74, 75, 77, 78, 79],
           dtype='int64'), 95014: Int64Index([65, 70, 72, 73, 76, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91,
            92, 93, 94, 95, 96, 97, 98, 99],
           dtype='int64'), 95051: Int64Index([15, 18, 23, 27, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 42, 43,
            44, 46, 49, 50, 51, 52, 54, 58],
           dtype='int64')}
[94085, 94087, 95014, 95051]


In [25]:
df.groupby("ZipCode").HomePriceK.describe()

count     mean        std     min     25%     50%     75%     max
ZipCode                                                                   
94085     25.0   885.96  34.408671   809.0   865.0   894.0   912.0   934.0
94087     25.0  1151.48  28.133788  1103.0  1128.0  1150.0  1179.0  1190.0
95014     25.0  1263.32  38.518091  1194.0  1240.0  1269.0  1288.0  1336.0
95051     25.0  1023.20  46.984927   942.0   991.0  1030.0  1068.0  1097.0

In [26]:
df.groupby("ZipCode").LotSize.describe()

count     mean         std     min     25%     50%     75%     max
ZipCode                                                                    
94085     25.0  6531.48  366.680279  6056.0  6183.0  6514.0  6870.0  7098.0
94087     25.0  8279.68  467.047439  7426.0  7958.0  8348.0  8585.0  8974.0
95014     25.0  9145.28  275.174266  8446.0  9095.0  9211.0  9337.0  9476.0
95051     25.0  7405.56  359.942134  6680.0  7181.0  7339.0  7693.0  8096.0

In [27]:
df.groupby("BedRooms").HomePriceK.describe()

count         mean         std     min     25%     50%     75%  \
BedRooms                                                                   
2          44.0  1026.659091  120.051141   831.0   917.0  1027.0  1138.0   
3          41.0  1068.365854  139.938693   809.0   949.0  1075.0  1181.0   
4          15.0  1274.866667   40.051514  1205.0  1251.0  1284.0  1297.0   

             max  
BedRooms          
2         1242.0  
3         1275.0  
4         1336.0

In [28]:
df.groupby("ZipCode").SchoolAPI.describe()

count    mean        std    min    25%    50%    75%    max
ZipCode                                                             
94085     25.0  907.00  38.223030  851.0  877.0  904.0  935.0  966.0
94087     25.0  899.24  33.121343  850.0  876.0  890.0  927.0  962.0
95014     25.0  894.80  32.430695  850.0  862.0  889.0  924.0  942.0
95051     25.0  916.68  39.359158  853.0  891.0  918.0  949.0  975.0

### Get Columns + Index

In [29]:
df.columns

Index(['HomeID', 'HomeAge', 'HomeSqft', 'LotSize', 'BedRooms', 'SchoolAPI',
       'CarGarage', 'ZipCode', 'HomePriceK', 'Price2019', 'Price2020'],
      dtype='object')

In [30]:
list(df.columns)

['HomeID',
 'HomeAge',
 'HomeSqft',
 'LotSize',
 'BedRooms',
 'SchoolAPI',
 'CarGarage',
 'ZipCode',
 'HomePriceK',
 'Price2019',
 'Price2020']

# <font color = "red">Pandas HW 1</font>

Could there be any relationship between "Zipcode" and "Price per lot size Sqft?" and "Zipcode" and Price per home Sqft?"" 
What can be the takeaway message from the data we have? Try out different functions to see if there is any significance?

In [40]:
# Your code here ...
df[["ZipCode", "LotSize", "HomePriceK"]].head(10)

ZipCode  LotSize  HomePriceK
0    94085     6056         894
1    94085     6085         861
2    94085     6089         831
3    94085     6129         809
4    94085     6141         890
5    94085     6148         867
6    94085     6183         843
7    94085     6186         820
8    94085     6233         874
9    94085     6276         885

In [133]:
result = df.groupby("ZipCode")["HomePriceK", "LotSize"].mean().values
# print(df.groupby("ZipCode")["HomePriceK", "LotSize"].mean().items)
# pd.Series(df.A.values,index=df.B).to_dict()

display(type(result))
display(result)

price_per_sqft = [round(lotsize/price, 2) for price,lotsize in result]
print(price_per_sqft)

print("\nMean lot size for each Zip code varies.\nThat said, there is a direct relationship between the Home Prices & Lot Size.")

numpy.ndarray

array([[ 885.96, 6531.48],
       [1151.48, 8279.68],
       [1263.32, 9145.28],
       [1023.2 , 7405.56]])

[7.37, 7.19, 7.24, 7.24]

Mean lot size for each Zip code varies.
That said, there is a direct relationship between the Home Prices & Lot Size.


# <font color = "red">Pandas HW 2</font>

What other data column for the zip codes could make the analysis more precise?

Median houshold income, population, population density??? Inlude one or more new data columns and re-visit your conclusions from HW 1.

Are these home prices driven by factors for which we have the data?

In [ ]:
# your code here ...

In [136]:
result = df.groupby("ZipCode")["HomePriceK", "LotSize", "HomeSqft"].mean().values

display(type(result))
display(result)

numpy.ndarray

array([[ 885.96, 6531.48, 1623.64],
       [1151.48, 8279.68, 1568.88],
       [1263.32, 9145.28, 1608.64],
       [1023.2 , 7405.56, 1659.96]])

In [138]:
price_per_sqft = [(round(lotsize/price, 2), round(homesqft/price, 2)) for price,lotsize,homesqft in result]
print(price_per_sqft)

[(7.37, 1.83), (7.19, 1.36), (7.24, 1.27), (7.24, 1.62)]


In [148]:
result[:1]

array([[ 885.96, 6531.48, 1623.64]])

In [2]:
print("There is no single feature that influence the price.\nPricePerSqft has closer relationship, but not the complete answer.")

There is no single feature that influence the price.
PricePerSqft has closer relationship, but not the complete answer.
