# Numpy

In [1]:
import numpy as np

# The Basics

In [4]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [6]:
b = np.array([[4.0,5.0,6.0],[1.0,2.0,3.0]])
print(b)

[[4. 5. 6.]
 [1. 2. 3.]]


In [7]:
# Get Dimension
a.ndim

1

In [8]:
# Get shape
b.shape

(2, 3)

In [9]:
# Get Type
a.dtype

dtype('int64')

In [11]:
aa = np.array([1,2,3], dtype='int8')
print(aa)
aa.dtype

[1 2 3]


dtype('int8')

In [13]:
# Get size in bytes
print(a.itemsize)
print(aa.itemsize)

8
1


# Accessing/Changing specific elements, rows, columns, etc

In [15]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [17]:
# Get a specific element [row, column]
print(a[1, 5])
print(a[1, -2])

13
13


In [18]:
# Get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [20]:
# Get a specific column
a[:,2]

array([ 3, 10])

In [44]:
# Getting a little more fancy [startindex:endindex:stepsize]
print(a[0, 1:6:2])
print(a[0, -6:-1:2])

[2 4 6]
[2 4 6]


In [45]:
a[1,5] = 20
print(a)

a[:,2] = [1,2]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


# 3-d example

In [52]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [53]:
# Get specific element (work outside in)
b[0,1,1]

4

In [54]:
b[:,0,0]

array([1, 5])

In [55]:
# replace
print(b)
b[:,1,:] = [[6,7],[8,9]]
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[[1 2]
  [6 7]]

 [[5 6]
  [8 9]]]


# Initializing different types of Arrays

In [57]:
# All 0's matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [58]:
# All 1's matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [59]:
# All other number
np.full((2,2), 99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [62]:
np.full(a.shape, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [61]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [66]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.96797115, 0.88481575],
       [0.28745382, 0.23471289],
       [0.10239635, 0.28606629],
       [0.86117844, 0.28803288]])

In [67]:
np.random.rand(2,2,2)

array([[[0.0642953 , 0.72702348],
        [0.78997057, 0.36993537]],

       [[0.66119502, 0.73390664],
        [0.30828888, 0.58108616]]])

In [68]:
np.random.random_sample(a.shape)

array([[0.98862815, 0.18497007, 0.54548387, 0.3195722 , 0.20264993,
        0.79408712, 0.5462369 ],
       [0.77964816, 0.02270475, 0.01801296, 0.10636782, 0.37834622,
        0.55331381, 0.07947835]])

In [71]:
# Random integer number (dice with max 1-6)
np.random.randint(1, 7, size=(3,3))

array([[3, 1, 5],
       [3, 2, 4],
       [3, 4, 2]])

In [72]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [78]:
np.eye(3, dtype='int8')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [82]:
np.eye(3, dtype=np.uint8)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=uint8)

In [85]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [90]:
output = np.ones((5,5), dtype=np.uint8)
print(output)

z = np.zeros((3,3), dtype=np.uint8)
z[1,1] = 9
print(z)

output[1:4, 1:4] = z
print(output)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 0 0]
 [0 9 0]
 [0 0 0]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


# Be careful when copying arrays!!

In [95]:
a = np.array([1,2,3])
b = a # b is point to a instead of creating a copy of a
b[0] = 100

print(a)
print(b)

[100   2   3]
[100   2   3]


In [96]:
a = np.array([1,2,3])
b = a.copy() # b has a copy of a
b[0] = 100

print(a)
print(b)

[1 2 3]
[100   2   3]


# Mathematics - Scalar operations

In [98]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [99]:
a+2

array([3, 4, 5, 6])

In [100]:
a - 2

array([-1,  0,  1,  2])

In [101]:
a * 2

array([2, 4, 6, 8])

In [102]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [103]:
a ** 2

array([ 1,  4,  9, 16])

In [104]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [105]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [106]:
b = np.array([1,1,2,2])
a + b

array([2, 3, 5, 6])

### for a lot more math routines... 
http://docs.scipy.org/doc/numpy/reference/routines.math.html

# Linear Algebra

In [113]:
a = np.ones((2,3), dtype=np.uint)
print(a)

b = np.full((3,2), 2, dtype=np.uint)
print(b)

c = np.matmul(a,b)
print(c)

[[1 1 1]
 [1 1 1]]
[[2 2]
 [2 2]
 [2 2]]
[[6 6]
 [6 6]]


In [115]:
# Find the determinant
d = np.identity(3)
np.linalg.det(d)

1.0

### more reference...
https://docs.scipy.org/doc/numpy/reference/routines.linalg.html

Determinant, Trace, Singular vector decomposition, eigenvalues, matrix norm, inverse, etc..

# Statistics

In [116]:
stats = np.array([[1,2,3],[4,5,6]])

In [119]:
np.min(stats)

1

In [120]:
np.min(stats, axis=0)

array([1, 2, 3])

In [121]:
np.min(stats, axis=1)

array([1, 4])

In [124]:
np.max(stats)

6

In [125]:
np.max(stats, axis=0)

array([4, 5, 6])

In [126]:
np.max(stats, axis=1)

array([3, 6])

In [127]:
np.sum(stats)

21

In [128]:
np.sum(stats, axis=0)

array([5, 7, 9])

In [129]:
np.sum(stats, axis=1)

array([ 6, 15])

In [130]:
np.mean(stats)

3.5

# Reorganizing arrays

In [131]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [132]:
after = before.reshape((8,1))
print(after)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [133]:
after = before.reshape((4,2))
print(after)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [135]:
after = before.reshape((2,2,2))
print(after)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [136]:
# Vertically stacking vectors

v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1, v2, v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [137]:
# Horizontal stack

h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1, h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# Miscellaneous

### Load data from file

In [142]:
file_data = np.genfromtxt('data.txt', delimiter=',')
file_data = file_data.astype(np.int32)
print(file_data)

[[  1  12  34 545  54  32  65  23]
 [  2 345  46 775 273   4 753  33]]


### Boolean masking & Advanced indexing

In [143]:
file_data > 50

array([[False, False, False,  True,  True, False,  True, False],
       [False,  True, False,  True,  True, False,  True, False]])

In [150]:
file_data[file_data > 50]

array([545,  54,  65, 345, 775, 273, 753], dtype=int32)

In [149]:
# you can index with a list in NumPy
a = np.array(range(1,10))
print(a)
a[[1,2,8]]

[1 2 3 4 5 6 7 8 9]


array([2, 3, 9])

In [154]:
np.any(file_data > 400, axis=0)

array([False, False, False,  True, False, False,  True, False])

In [157]:
((file_data > 50) & (file_data < 100))

array([[False, False, False, False,  True, False,  True, False],
       [False, False, False, False, False, False, False, False]])

In [159]:
file_data[((file_data > 50) & (file_data < 100))]

array([54, 65], dtype=int32)

In [171]:
a = np.random.randint(1,7,size=(5,5))
print(a)

[[5 5 4 2 5]
 [2 4 1 4 5]
 [2 6 1 3 1]
 [6 3 3 6 1]
 [3 3 3 5 5]]


In [172]:
print(a[2:4, 0:2])

[[2 6]
 [6 3]]


In [173]:
print(a[[0,1,2,3],[1,2,3,4]])

[5 1 3 1]


In [178]:
print(a[[0,3,4],3:])

[[2 5]
 [6 1]
 [5 5]]
